// app/layout

import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin", "cyrillic"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal"],
  display: "swap",
  preload: true,
  fallback: ['system-ui', 'sans-serif']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="uk">
      <body className={`${dmSans.variable} antialiased`}>
        {children}
        {modal}
      </body>
    </html>
  );
}
